services:
  
  api-java:
    extends:
      file: ./api-java/docker-compose.yaml
      service: api-java
    depends_on:
      - rabbitmq
      
  api-nestjs:
    extends:
      file: ./api-nestjs/docker-compose.yaml
      service: api-nestjs  
    depends_on:
      - rabbitmq

  api-flask:
    extends:
      file: ./api-flask/docker-compose.yaml
      service: api-flask
    depends_on:
    - rabbitmq

  api-golang:
    extends:
        file: ./api-golang/docker-compose.yaml
        service: api-golang
    depends_on:
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data    

networks:
  backend:
    driver: bridge
